### PR TITLE
Implement inverseResourceOffers

### LINKED ISSUE #57: Support InverseOffers
Currently, if a maintenance schedule is posted to the Mesos master, the current assumption in `process_event` lead to a `KeyError` when trying to extract non-existent offers from an OFFERS message. Here is an example of an event which causes this issue.

```
{
	"offers": {
		"inverse_offers": [
			{
				"url": {
					"path": "/slave(1)",
					"scheme": "http",
					"address": {
						"ip": "10.112.46.15",
						"hostname": "mesos-dev2.hostname.io",
						"port": 5051
					}
				},
				"unavailability": {
					"start": {
						"nanoseconds": 1488897610000000000
					}
				},
				"framework_id": {
					"value": "142e3612-a19d-4be2-9f06-35a987fd36fb-0024"
				},
				"agent_id": {
					"value": "7f05b67b-6a40-4c90-aeef-782616a5ae9d-S3"
				},
				"id": {
					"value": "142e3612-a19d-4be2-9f06-35a987fd36fb-O230842"
				}
			}
		]
	},
	"type": "OFFERS"
}
```

I'm working to support inverse offers at https://github.com/efritz/pymesos.

### PR DESCRIPTION
**Pull request by efritz**
This should fix #57. If the changes to the interface seem strange, I'd like to discuss alternative choices that would support this feature.

### CODE REVIEW

**Comment by windreamer** [comment]
@haosdent can you help me to comfirm if the interface change is OK?

**Comment by haosdent** [comment]
@kaysoky implement an example about how to use inverseOffer, may refer https://github.com/kaysoky/InverseOfferExampleFramework/blob/master/example.cpp#L198-L209

**Comment by efritz** [comment]
Would `inverseOffers` be a better name for the interface?

**Comment by windreamer** [comment]
@efritz I think `inverseOffers` is better
thanks for the PR

**Comment by efritz** [comment]
Thanks! Would it be possible to bump the version and make this version accessible through PyPI?

**Comment by windreamer** [comment]
Of coz! We are just evaluated the new version, and will release it soon.

**Comment by efritz** [comment]
Great news! Thanks so much.

**Pull request merged**
